### ISSUE TITLE
How to Connect to Alexa Developer Console?

### ISSUE THREAD

**Issue by hoffm386** [anjishnu/ask-alexa-twitter#1]
Hi!  I'm working on creating a set of OAuth examples for Alexa in JavaScript for use with AWS Lambda.  Your code is very readable and helpful in understanding what exactly a LinkAccount card looks like, since the [documentation](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/linking-an-alexa-user-with-a-user-in-your-system) doesn't quite spell it out.

However, I don't see in your README how to link this to the Alexa Skills Portal itself.  Specifically the "Account Linking" section which asks for things like Authorization URL.  Is there a URL from Twitter itself that works for this, or did you have to create your own web page that used the Twitter API?  The documentation link above assumes that you are making a skill for your own service, not a third-party one, so I'm not sure what to look for.  This is the section I'm talking about, on the "ALEXA" tab of the Amazon Developer Console:
![screenshot of Account Linking Section of Alexa Developer Console](https://cloud.githubusercontent.com/assets/2507951/17796677/5b9a64a4-6577-11e6-86a5-723784d5755c.png)

Thanks!

**Comment by anjishnu** [comment]
I implemented this as a passthrough - basically I got a page from twitter as an http response and then served/redirected it though my own end point. That's what the 'authenticate_user_page' function is doing (look at server.py) it calls twitter to get the page, then serves it through my own URL.
